### ISSUE TITLE
 no issue of news articles

### ISSUE THREAD

**Issue by Neofine82** [cdaecke/md_news_author#10]
Hello, 
I have noticed a problem with the issue of news articles in the detail view of an author. The news record is assigned to the respective author via the author tab. Nevertheless, the news article appears with another person. I can not see the connection from Show.html. I ask for support. Thanks a lot!

Typo3 8.7.24
news 7.3.1
md_news_author 4.0.0

**Comment by cdaecke** [comment]
One news record can be attached to multiple authors. Could you please check, if the news article you are talking about is connected to the other person as well?

**Comment by Neofine82** [comment]
An article is only linked to one person. But I also tested the case with two authors for one article.

**Comment by Neofine82** [comment]
Only one record per author is output. No matter how many articles I give to an author.

**Comment by cdaecke** [comment]
Please add the following line to the template `Show.html` and paste a screenshot here

    <f:debug>{_all}</f:debug>

**Comment by Neofine82** [comment]
![1](https://user-images.githubusercontent.com/52271957/70793163-08067a00-1d9b-11ea-8bb3-dc3f3dbba5ec.jpg)
![2](https://user-images.githubusercontent.com/52271957/70793164-089f1080-1d9b-11ea-925c-0e59de1cc9f5.jpg)
![3](https://user-images.githubusercontent.com/52271957/70793165-089f1080-1d9b-11ea-94f7-d1c921e30f2f.jpg)

**Comment by Neofine82** [comment]
No article is actually issued here. Although two records are assigned.

**Comment by cdaecke** [comment]
Thanks for the info, I can confirm the issue.

I have to double check, and will get back to you.

**Comment by Neofine82** [comment]
This is really great. Many thanks

**Comment by cdaecke** [comment]
Please find attached my bugfix. Can you confirm, that this is working for you?

**Comment by Neofine82** [comment]
Really great! I can confirm the functionality. Both multiple linking and individual linking of the data record News with authors. Great thank you

**Comment by cdaecke** [comment]
Thanks for your feedback!

I even found a better way to query the news records, so I could rely on the default extbase methods. Could you please confirm, whether it is still working for your?

**Comment by Neofine82** [comment]
Works great!

**Comment by Neofine82** [comment]
A query for the social box and news records would also be necessary. If none are available, the heading is output.

**Comment by cdaecke** [comment]
Thanks again for your feedback!
What exactly do you mean with "the social box"?

**Comment by Neofine82** [comment]
I mean the information about social links. It's my fault. I added a heading that shows no entries. Now I've added a condition that doesn't appear until a phone number or other contact information is entered. The heading in the section with the ID author-articles is also output without news articles.

**Comment by cdaecke** [comment]
A new version of the extension is published.

Thanks again for reporting!
