### ISSUE TITLE
Real URL

### ISSUE THREAD

**Issue by Neofine82** [cdaecke/md_news_author#11]
Hey, I can not configure the Real URL so that the detail pages get a nice URL. The hash is current: 
/?tx_mdnewsauthor_newsauthor%5BnewsAuthor%5D=7&tx_mdnewsauthor_newsauthor%5Baction%5D=show&tx_mdnewsauthor_newsauthor%5Bcontroller%5D=NewsAuthor&cHash=fa4a167f199bef1e7216e7919182fcc4

Unfortunately, I don't have much experience configuring the paths either. 
I hope for your support. :-)

**Comment by Neofine82** [comment]
I completely forgot. The project is still built with Typo3 V8. realurl_conf.php I created the code from the documentation, unfortunately without success. 
Automatic creation of autoconf.php was still active.

**Comment by cdaecke** [comment]
It's not easy to tell, why it is not working, the configuration in the documentation should work.

I would check the following:

- is the configuration inserted into the right place in the realUrl config array (`'postVarSets' => ['_DEFAULT' => ...]`
- is the realUrl config loaded. Check the path for `basic.configFile` in the extension settings
- last but not least: clear all caches after changing the relaurl config

**Comment by cdaecke** [comment]
@Neofine82 As I didn't hear from you, I guess you could solve your issue. If not, let me know.
