### ISSUE TITLE
Backend user as author

### ISSUE THREAD

**Issue by zelcode** [cdaecke/md_news_author#12]
Hi,

is it possible to preselect current backend user as news author, most of the time this is the case, it would be great time saver for editors.

Regards.

**Comment by cdaecke** [comment]
You can preselect an author for a backend user with the following User TSconfig.

Edit the user, switch to the tab `Options` and enter the following line in the field `TSconfig`:

    TCAdefaults.tx_news_domain_model_news.news_author = 101

Replace `101` with the `uid` of the author in the table `tx_mdnewsauthor_domain_model_newsauthor`.

See documentation [here](https://docs.typo3.org/m/typo3/reference-tsconfig/master/en-us/UserTsconfig/TcaDefaults.html).
