### ISSUE TITLE
Hi,are there plans to upgrade to TYPO3v10?

### ISSUE THREAD

**Issue by jooler** [cdaecke/md_news_author#13]
I've used this extension in my site,but it not work for TYPO3v10,
so 
are there plans for v10?

**Comment by cdaecke** [comment]
Yes, I am planing to update the extension for TYPO3 10 within the next few weeks.

**Comment by jooler** [comment]
It's very excitiing,Thanks for your work!

**Comment by cdaecke** [comment]
Version 5.0.0 of the extension is released.
