### ISSUE TITLE
some problem with "News 8.4.0"

### ISSUE THREAD

**Issue by jooler** [cdaecke/md_news_author#14]
Dear chris,
Extension works on TYPO3v10 with News 8.3.0, But when I upgrade News Extension to V8.4.0, Works well on backend but there's nothing on frontend, 

nothing was founded when I check debug information(add <f:debug>{_all}</f:debug> in template)
no newsAuthor's field in debug information

I've add a element content "News Author -> list author" I got this
![004](https://user-images.githubusercontent.com/25960405/92707339-c9343d80-f387-11ea-9986-757ac12e1aa2.png)
and in /var/log, 

`Thu, 10 Sep 2020 17:06:04 +0800 [ERROR] request="9c2f05723f441" component="TYPO3.CMS.Frontend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed. - {"expression":"globalVar = LIT:1 = 1"}
Thu, 10 Sep 2020 17:06:04 +0800 [ERROR] request="9c2f05723f441" component="TYPO3.CMS.Frontend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed. - {"expression":"globalVar = LIT:1 = 1"}
Thu, 10 Sep 2020 17:06:05 +0800 [CRITICAL] request="9c2f05723f441" component="TYPO3.CMS.Core.Error.ProductionExceptionHandler": Core: Exception handler (WEB): Uncaught TYPO3 Exception: Argument 2 passed to TYPO3\CMS\Core\Utility\ArrayUtility::mergeRecursiveWithOverrule() must be of the type array, null given, called in /www/wwwroot/t3/public/typo3/sysext/fluid/Classes/ViewHelpers/Widget/Controller/PaginateController.php on line 76 | TypeError thrown in file /www/wwwroot/t3/public/typo3/sysext/core/Classes/Utility/ArrayUtility.php in line 621. Requested URL: http://rms.lc/products - {"TYPO3_MODE":"FE","exception":{}}
`

please check it
thanks for your work and sorry for my bad englist.

**Comment by cdaecke** [comment]
Thanks for reporting!

I was able to reproduce this error and just pushed a bug fix. Could you please double check with the current master, if this fixes your problem too?

**Comment by jooler** [comment]
> Thanks for reporting!
> 
> I was able to reproduce this error and just pushed a bug fix. Could you please double check with the current master, if this fixes your problem too?

It works , thanks for your working.

**Comment by cdaecke** [comment]
v5.0.1 is released.
