### ISSUE TITLE
PostgreSQL 12.5 error

### ISSUE THREAD

**Issue by plojewski** [cdaecke/md_news_author#15]
Hi, when I edit news I've go an error and can't search author in Author tab:

`Database Error SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for type integer: "FALSE" LINE 1: ... OR tx_mdnewsauthor_domain_model_newsauthor.pid = 'FALSE' ) ... ^. A SQL error occurred. This may indicate a schema mismatch between TCA and the database. Try running database compare in the Install Tool.`

DB analyzer looks fine.

**Comment by plojewski** [comment]
Typo3: 10.4.16
News: 8.5.2
md_news_author: 5.0.1

**Comment by cdaecke** [comment]
This seems to be an issue with PostgreSQL, it is not reproducible with MariaDB/MySQL. A workaround could be to set the page Uid of the page, where the authors are stored, see [Page TSconfig](https://github.com/cdaecke/md_news_author#page-tsconfig). This is of course only feasible, if all authors are stored in the same page.

Is this working for you?

**Comment by plojewski** [comment]
@cdaecke Thank you! Setting TCEFORM.tx_news_domain_model_news.news_author.PAGE_TSCONFIG_STR works for me.
