### ISSUE TITLE
Fatal error: Cannot redeclare GeorgRinger\News\Domain\Model\News::$newsAuthor

### ISSUE THREAD

**Issue by marcelmarty** [cdaecke/md_news_author#18]
The following line (Line 44) in ext_localconf.php: 
`$GLOBALS['TYPO3_CONF_VARS']['EXT']['news']['classes']['Domain/Model/News'][] = 'md_news_author';`

generates the following error within the extension manager, if I install an other extension by extension manager in a legacy installation:
`Fatal error: Cannot redeclare GeorgRinger\News\Domain\Model\News::$newsAuthor in D:\webserver\foo.bar.ch\public_html\typo3temp\var\cache\code\news\tx_news_domain_model_news.php on line 1729`

Version informations:
- TYPO3 11.5.1 (legacy installation)
- PHP 7.4.24
- news 9.0.0-dev
- md_news_author 6.0.3

If I comment out the line 44 in ext_localconf.php of the extension, the error does not occur anymore.

**Comment by cdaecke** [comment]
@marcelmarty Is now everything working with the current versions of `ext:news` and `ext:md_news_author`?
