### ISSUE TITLE
PHP dependency

### ISSUE THREAD

**Issue by tdeuling** [cdaecke/md_news_author#19]
Please add a dependency in composer.json/ext_emconf.php for PHP. This extension won't work with PHP 7.2.

**Comment by cdaecke** [comment]
Where exactly do you see a problem with PHP 7.2.x?

**Comment by tdeuling** [comment]
![Selection_834](https://user-images.githubusercontent.com/1298841/155740438-c92cd0b4-465e-4270-b308-2df490c8940e.png)

**Comment by cdaecke** [comment]
Thanks a lot for the hint! The attached commit will fix this.

**Comment by cdaecke** [comment]
v6.0.7 is released.
