### ISSUE TITLE
Not ready for news v.10

### ISSUE THREAD

**Issue by martin-git-kristensen** [cdaecke/md_news_author#20]
in ext_emconf.php news is not ready for news v.10 - but in composer.json the constraints is ok for news v. 10

constraints' => [
        'depends' => [
            'typo3' => '10.4.0-11.5.99',
            'news' => '7.0-9.99',
            'numbered_pagination' => '1.0.1-1.99.99',
        ],
]

**Comment by martin-git-kristensen** [comment]
it is also a problem in composer.json where news is only in 10.0 and the news is actually 10.0.2
require": {
        "typo3/cms-core": ">=10.0,<12.0",
        "georgringer/news": ">=7.0,<10.0",
        "georgringer/numbered-pagination": ">=1.0.1,<2.0.0"
    },

**Comment by cdaecke** [comment]
Dependency to ext:news is updated with new release (v6.0.8).
