### ISSUE TITLE
TYPO3 12 compatibility

### ISSUE THREAD

**Issue by Tim-Obert** [cdaecke/md_news_author#21]
Hi, 

are there any plans for TYPO3 12 LTS?

Thanks!

**Comment by cdaecke** [comment]
Yes, the extension will be available for TYPO3 v12.

**Comment by nilesh-nitsan** [comment]
Is it released by this month or next month? When will be a plan to release any roadmap?

**Comment by nitsan-technologies** [comment]
Hey Guys,

@Tim-Obert 
We have a fork and make it compatible with TYPO3 v12.

@cdaecke 
Would you like us to create a pull request? We have improved a few things, e.g., Removed dependencies of EXT:numbered_pagination 

Cheers, Team NITSAN

**Comment by cdaecke** [comment]
@nitsan-technologies Yes, pull requests are always welcome! :-)

**Comment by stigfaerch** [comment]
@nitsan-technologies 
No pull request?

**Comment by nitsan-technologies** [comment]
Oh sorry! Missed to let know, we have forked with https://github.com/nitsan-technologies/ns_news_author (because of some re-factors and removed other extensions dependencies). Feel free to ask if you need any support at our Git-repo.

**Comment by cdaecke** [comment]
I have just updated the code to be compatible with TYPO3 v11 and v12.

Could you please give it a try and do some testing?

**Comment by Schweriner** [comment]
@cdaecke works fine for me, thanks.

**Comment by cdaecke** [comment]
@Schweriner Thanks for testing!

A new version of the extension is released.
