### ISSUE TITLE
Some column definitions could be removed from TCA

### ISSUE THREAD

**Issue by jonaseberle** [cdaecke/md_news_author#22]
Hi, happy New Year and thanks for your extension!

Some column definitions could be removed from the [TCA](https://github.com/cdaecke/md_news_author/blob/master/Configuration/TCA/tx_mdnewsauthor_domain_model_newsauthor.php) as they are [auto-created for TYPO3 v9+](https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/9.3/Feature-85160-AutoCreateManagementDBFieldsFromTCACtrl.html) when used in `ctrl`:

`sys_language_uid`, `l10n_parent`, `l10n_diffsource`, `hidden`, `starttime`, `endtime`.

`t3ver_label` [is not used in TYPO3 v10+](https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/10.0/Breaking-87193-DeprecatedFunctionalityRemoved.html?highlight=t3ver_label) (and the other workspace fields also get auto-created).

I can create a PR if you want.

**Comment by cdaecke** [comment]
Hi @jonaseberle and all the best for the New Year for you too!

I am very happy, if you provide a pull request :-)

**Comment by cdaecke** [comment]
I have removed the `t3ver_label` from the TCA definition.

Thanks, for your finger tip!
