### ISSUE TITLE
Compatibility with numbered-pagination 2.0.0

### ISSUE THREAD

**Issue by PeterProell** [cdaecke/md_news_author#25]
**composer req mediadreams/md_news_author "^7"** 
has problems with the current numbered-pagination:
mediadreams/md_news_author v7.0.0 requires georgringer/numbered-pagination >=1.0.1,<2.0.0 -> found georgringer/numbered-pagination[1.0.1, ..., 1.0.5] but it conflicts with your root composer.json require (^2.0).

**Comment by cdaecke** [comment]
Thanks for the hint!
