### ISSUE TITLE
Version mismatch between composer.json and ext_emconf.php

### ISSUE THREAD

**Issue by ayacoo** [cdaecke/md_news_author#26]
Hi, I noticed during a TYPO3 upgrade that I was warned about the EXT update. The trigger in this case was the ext_emconf.php (classic way)

**composer.json**

```
    "require": {
        "typo3/cms-core": ">=11.0,<13.0",
        "georgringer/news": ">=9.0,<12.0",
        "georgringer/numbered-pagination": ">=1.0.1,<3.0.0"
    },
```

**ext_emconf.php**

```
        'depends' => [
            'typo3' => '11.5.0-12.4.99',
            'news' => '9.0-11.99',
            'numbered_pagination' => '1.0.1-1.99.99',
        ],
```

The value for numbered_pagination still needs to be adjusted.

**Comment by cdaecke** [comment]
Thanks for pointing this out.
This is fixed and a news version of the extension released.
