### ISSUE TITLE
Author link on the news detail view 

### ISSUE THREAD

**Issue by in-session** [cdaecke/md_news_author#3]
Hi,

I hope you can help me, I have a small problem to show the author on the detail view of the news extension.

**I changed the follow parts of the constants:**
`
plugin.tx_mdnewsauthor {
  settings {
    authorDetailPid = 57
    newsDetailPid = 34
}
}
`

**I add the link inside the detail view of the news ext:**
`
<f:link.action action="show" controller="NewsAuthor" extensionName="mdnewsauthor" pluginName="newsauthor" arguments="{newsAuthor: newsItem.newsAuthor}" pageUid="{settings.newsAuthor.authorDetailPid}" title="More about {md:ShowAuthorName(author:'{newsItem.newsAuthor}')}">
    {md:ShowAuthorName(author:'{newsItem.newsAuthor}')}
</f:link.action>
`

**Also the viewhelper:**
`{namespace md=Mediadreams\MdNewsAuthor\ViewHelpers}`
or
`<html xmlns:f="http://typo3.org/ns/TYPO3/CMS/Fluid/ViewHelpers"
	  xmlns:n="http://typo3.org/ns/GeorgRinger/News/ViewHelpers"
	  xmlns:rx="http://typo3.org/ns/Reelworx/RxShariff/ViewHelper"
      xmlns:md="http://typo3.org/ns/Mediadreams/MdNewsAuthor/ViewHelpers"
	  data-namespace-typo3-fluid="true">`

**But I get the follow error:**
Call to undefined method TYPO3\CMS\Extbase\Persistence\Generic\LazyObjectStorage::getTitle() 
Error thrown in file
/html/typo3/typo3conf/ext/md_news_author/Classes/ViewHelpers/ShowAuthorNameViewHelper.php in line 64.

**Versions:**
Typo3 8.7.8
News: 6.1.1
PHP: 7.1
md_news_author: current github version

Thanks for your help, cheers chris

**Comment by cdaecke** [comment]
Hi,
for version 3.x you need to iterate through the authors in the news templates:
 
    <f:for each="{newsItem.newsAuthor}" as="author">
        <f:link.action action="show" controller="NewsAuthor" extensionName="mdnewsauthor" pluginName="newsauthor" arguments="{newsAuthor: author}" pageUid="{settings.newsAuthor.authorDetailPid}" title="More about {md:ShowAuthorName(author:'{author}')}">
            <md:ShowAuthorName author="{author}" />
        </f:link.action>
    </f:for>

I will publish the final version 3 these days which will serve an updated documentation.

**Comment by cdaecke** [comment]
The finale version 3.0.0 with updated documentation is released now. Is everything working for you?

**Comment by in-session** [comment]
Works fine many thanks, additional an RealUrlAutoConfiguration will be great for the extension.
