### ISSUE TITLE
Translation 

### ISSUE THREAD

**Issue by n1klas** [cdaecke/md_news_author#6]
I am using tx_news 6.3.0 and md_news_author 3.0.1. When i translate author records, the translated record will be double assignd to the news record (in both languages). Also i can not see wich record is English/German in the multiselect TCA.

**Comment by cdaecke** [comment]
Sorry for the late feedback. As I am very busy at the moment I don't have the time to look at this issue right now. Pull requests are very welcome!

**Comment by cdaecke** [comment]
@n1klas Would you be able to double check this fix?

**Comment by cdaecke** [comment]
@n1klas You will find the version 3.0.2 of the extension in the TER. This contains the fixes about the langauge issues. Thanks again for reporting!
