### ISSUE TITLE
ext:md_news_author for TYPO3 9.x.x will be?

### ISSUE THREAD

**Issue by typo3ua** [cdaecke/md_news_author#8]
When will be ext: md_news_author for TYPO3 9.x.x ?

**Comment by cdaecke** [comment]
I will try to update the extension for TYPO3 9.x within the next view weeks.

**Comment by cdaecke** [comment]
@typo3ua You can find the current status quo in the branch [TYPO3_9_compatibility](https://github.com/cdaecke/md_news_author/tree/release/TYPO3_9_compatibility). Are you able to test it?

**Comment by cdaecke** [comment]
Version 4.0.0 is released which supports TYPO3 9.
