### ISSUE TITLE
Show Image from the news - in show.html

### ISSUE THREAD

**Issue by edekowalski** [cdaecke/md_news_author#9]
Dear Developer,

how can i show in show.html the news with image from the news.

Best Regards and thank you for help!
E.K

**Comment by cdaecke** [comment]
At the moment this is not possible out of the box. But...

You can get the image with typoscript:

    lib.newsImg = FILES
    lib.newsImg {
        references {
            table = tx_news_domain_model_news
            uid.current = 1
            uid.wrap = |
            fieldName = fal_media
        }

        begin = 0
        maxItems = 1

        renderObj = IMAGE
        renderObj {
            file.import.data = file:current:publicUrl
            file.maxW = 100
            wrap = |
        }
    }

And use this in your fluid template:
    <f:cObject typoscriptObjectPath="lib.newsImg">{newsItem.uid}</f:cObject>

Hope this helps!

**Comment by edekowalski** [comment]
**Thank your very much!**! It work's fine for me.

Best Regard's
Ede

**Comment by cdaecke** [comment]
Just to let you know:
With version 4.0.1 which was just released, you will get all images like you would get them with a "normal" news record. So you don't need the Typoscript anymore.
